CREATE DATABASE LAB_01;

USE LAB_01;

CREATE TABLE CLIENTE (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR (50),
SOBRENOME VARCHAR (50)
);

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE (ID, NOME, SOBRENOME)
VALUES (1, 'José', 'Silva');

INSERT INTO CLIENTE (ID, NOME, SOBRENOME)
VALUES
(2, 'Ary', 'Farah'),
(3, 'Adriano', 'Vale'),
(4, 'Carol', 'Assis'),
(5, 'Ícaro', 'Lima');

UPDATE CLIENTE
SET NOME	  = 'Selma',
	SOBRENOME = 'Maria'
WHERE ID = 3;

UPDATE CLIENTE
SET SOBRENOME = 'Alves'
WHERE ID = 3 OR ID = 1;

DELETE
FROM CLIENTE
WHERE ID = 3;

